### ISSUE TITLE
Restic installation directory chmod

### ISSUE THREAD

**Issue by pestaa** [paulfantom/ansible-restic#12]
Hi, thanks for this project.

The binary gets installed to /usr/local/bin, but the task named "Ensure restic installation directory exist" overwrites the folder's permissions, effectively disabling access to other binaries in that folder for regular users.

I checked Ansible's file module but it states that the directory is created only if it doesn't exist. I've found no option to let existing permissions stay intact.

**Comment by paulfantom** [comment]
@pestaa could you check if my fix from #13 works for you?

**Comment by pestaa** [comment]
Thanks for the quick fix, it looks like it should work as intended, though I had to work around and move on.
