### ISSUE TITLE
Request to publish a new tag for PR#61

### ISSUE THREAD

**Issue by shalomb** [paulfantom/ansible-restic#62]
Hi @paulfantom - We're wanting to take on the improvement in https://github.com/paulfantom/ansible-restic/pull/61 (check if a repo needs initialization) but this hasn't been _released_ in a tag. We'd very much appreciate it, if you would please make new tag/release so we can refer to that in our deployments?

**Comment by paulfantom** [comment]
Done with https://github.com/paulfantom/ansible-restic/releases/tag/0.15.0

**Comment by shalomb** [comment]
:1st_place_medal:
